/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };

const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'JavaScript',
      link: {
        type: 'generated-index',
        title: 'JavaScript',
        description: "JavaScript学习文档记录",
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Promise',
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Promise',
            description: "Promise学习文档记录",
          },
          items: [
            'front-end/javaScript/promise/promise使用',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
