/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };

const sidebars = {
  docs: [
    'intro',
    {
      label: 'JavaScript',
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'JavaScript',
      },
      collapsed: true,
      items: [
        {
          label: 'Promise',
          type: 'category',
          collapsed: true,
          items: [
            'front-end/javaScript/promise/promise使用',
            'front-end/javaScript/promise/promise实现',
          ],
        },
      ],
    },
    {
      label: '算法学习',
      type: 'category',
      link: {
        type: 'generated-index',
        title: '算法学习',
        description: "主要通过代码随想录的文档进行算法学习",
      },
      items: [
        {
          label: '数组',
          type: 'category',
          collapsed: true,
          items: [
            'algorithm/array/704-二分查找',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
