/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };

const sidebars = {
  docs: [
    'intro',
    {
      label: 'JavaScript',
      type: 'category',
      collapsed: true,
      items: [
        {
          label: 'Promise',
          type: 'category',
          collapsed: true,
          items: [
            'front-end/javaScript/promise/promise使用',
            'front-end/javaScript/promise/promise实现',
          ],
        },
        'front-end/javaScript/JS模块化/JS_module',
      ],
    },
    {
      label: 'TypeScript',
      type: 'category',
      items: [
        'front-end/typeScript/为什么使用TypeScript',
        'front-end/typeScript/开始使用TypeScript',
        'front-end/typeScript/原始数据类型',
        'front-end/typeScript/其他常见类型',
        'front-end/typeScript/模块与命名空间',
        'front-end/typeScript/类型推导',
        'front-end/typeScript/枚举类型',
        'front-end/typeScript/联合类型',
      ],
    },
    {
      label: '算法学习',
      type: 'category',
      items: [
        'algorithm/1.两数之和',
        'algorithm/2.两数相加',
        'algorithm/20.有效的括号',
        'algorithm/21.合并两个有序链表',
        'algorithm/26.删除有序数组中的重复项',
        'algorithm/704.二分查找',
      ],
    },
  ],
};

module.exports = sidebars;
